### ISSUE TITLE
TypeError: Cannot read property 'comclass' of undefined

### ISSUE THREAD

**Issue by fraser73** [OpenZWave/node-red-contrib-openzwave#25]
#I've started to see a problem with Node Red contrib Openzwave, in that node-red dies when it receives some (not all) messages in from the zwave network, it also doesn't seem to receive some:

```
Welcome to Node-RED
===================

17 Jun 09:28:16 - [info] Node-RED version: v0.13.4
17 Jun 09:28:16 - [info] Node.js  version: v0.10.29
17 Jun 09:28:16 - [info] Linux 4.1.19-v7+ arm LE
17 Jun 09:28:16 - [info] Loading palette nodes

/usr/lib/node_modules/node-red-contrib-openzwave/node_modules/getmac/node_modules/extract-opts/source/index.js:6
module.exports = function (opts, next, config = {}) {
                                              ^
17 Jun 09:28:25 - [info] Settings file  : /usr/lib/node_modules/node-red/settings.js
17 Jun 09:28:25 - [info] User directory : /var/node-red/
17 Jun 09:28:25 - [info] Flows file : /var/node-red/flows_frinkhub01.frinkiac7.net.json
17 Jun 09:28:25 - [info] Server now running at http://127.0.0.1:1880/
17 Jun 09:28:26 - [info] Starting flows
Initialising OpenZWave 1.4.164 binary addon for Node.JS.
	OpenZWave Security API is ENABLED
	ZWave device db    : /usr/local/etc/openzwave/
	User settings path : /usr/lib/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/build/Release/../../
	Option Overrides : --Logging false --ConsoleOutput false --QueueLogLevel 6
17 Jun 09:28:27 - [info] [inject:Hourly delete] repeat = 3600000
17 Jun 09:28:29 - [info] [inject:Trigger] repeat = 60000
17 Jun 09:28:31 - [info] [inject:4d262a20.ebbaec] crontab = 00 23 * * *
17 Jun 09:28:31 - [error] [sun events:Suncalc] No latitude or longitude set.
17 Jun 09:28:31 - [info] [sun events:Suncalc] Calculating sun event times for undefined, undefined.
17 Jun 09:28:32 - [info] [inject:b5610f9.d1031f] crontab = 00 23 * * *
17 Jun 09:28:33 - [error] [e-mail:REMOVED] No e-mail userid set
17 Jun 09:28:33 - [error] [e-mail:REMOVED] No e-mail password set
17 Jun 09:28:33 - [info] Started flows
17 Jun 09:28:35 - [error] [function:Obtain data from global var] TypeError: Cannot read property '1' of undefined
17 Jun 09:28:35 - [info] serial port /dev/currentcost opened at 57600 baud 8N1
17 Jun 09:28:36 - [info] [file:bcb1b30.03f1a1] wrote to file: /tmp/zwave.json
17 Jun 09:28:37 - [info] [mqtt-broker:8552f64b.80b9c] Connected to broker: mqtt://localhost:1883
17 Jun 09:29:29 - [error] [function:Obtain data from global var] TypeError: Cannot read property '1' of undefined
17 Jun 09:29:29 - [info] [file:bcb1b30.03f1a1] wrote to file: /tmp/zwave.json
17 Jun 09:29:44 - [red] Uncaught Exception:
17 Jun 09:29:44 - TypeError: Cannot read property 'comclass' of undefined
    at EventEmitter.nodeEvent (/usr/lib/node_modules/node-red-contrib-openzwave/10-zwave.js:216:24)
    at EventEmitter.emit (events.js:106:17)
    at addonModule.Emitter.emit (/usr/lib/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)
root@frinkhub01:/usr/lib/node_modules/node-red# 

````

The particular problem seen above is caused by manually switching a TKB TZ66D in wall switch module, some of my devices don't seem to be able to send messages to the network (TKB plug in modules, and possibly my thermostat) however others seem absolutely fine. I have totally rebuilt the pi from scratch and see the same propblem - Any ideas?

**Comment by fraser73** [comment]
I just updated node.js to version 0.12.13 and node-red to 0.14.3, I still get the same problem.

**Comment by ekarak** [comment]
please do an npm update of the NR plugin to version 1.1.7 - there is no valueID passed on from the C++ library from the Type_NodeEvent notification, so I've removed everything else but the node and event ID's.

**Comment by fraser73** [comment]
Excellent, that seems to have done the job, thanks very much.
