### ISSUE TITLE
Installing on Docker (RPi)

### ISSUE THREAD

**Issue by Qaldak** [OpenZWave/node-red-contrib-openzwave#69]
Hi all

I run Node-Red in Docker on my Raspberry Pi.
Now, I would like to install node-red-contrib-openzwave to connect my Fibaro Motion Sensor.

But I can not install this node. I tried to install the openzwave library and openzwave-shared, like desciped in this post: https://github.com/OpenZWave/node-red-contrib-openzwave/issues/61#issuecomment-405163171
But install failed each try.

Log:
```
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm http fetch GET 304 https://registry.npmjs.org/openzwave-shared 517ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 131ms (from cache)
npm info lifecycle openzwave-shared@1.5.6~preinstall: openzwave-shared@1.5.6
npm info lifecycle nan@2.14.0~preinstall: nan@2.14.0

> openzwave-shared@1.5.6 preinstall /usr/src/node-red/node_modules/openzwave-shared
> node lib/install-ozw.js

npm info linkStuff openzwave-shared@1.5.6
npm info linkStuff nan@2.14.0
npm info lifecycle openzwave-shared@1.5.6~install: openzwave-shared@1.5.6

> openzwave-shared@1.5.6 install /usr/src/node-red/node_modules/openzwave-shared
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/src/node-red/node_modules/openzwave-shared/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/src/node-red/.node-gyp/8.1.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/src/node-red/.node-gyp/8.1.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/src/node-red/.node-gyp/8.1.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/src/node-red/node_modules/openzwave-shared',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
grep: /usr/*/include/value_classes: No such file or directory
gyp: Call to 'grep -r GetTypeNameFromEnum /usr/*/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.14.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/node-red/node_modules/openzwave-shared
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm info lifecycle openzwave-shared@1.5.6~install: Failed to exec install script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2019-07-17T19_47_45_676Z-debug.log
```

Am I on the right track?

~~I did try to install via "docker exec", but it asks me always for node-red password.
What is the node-red password? Do I have to change settings.js (AdminAuth)? If yes, how I have to do it?~~

I can connect via "docker exec -it -u root node-red /bin/bash" but I couldn't install the packages.

If I install openzwave-shared, I got following error
```
grep: /usr/*/include/value_classes: No such file or directory
gyp: Call to 'grep -r GetTypeNameFromEnum /usr/*/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.14.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/node-red/node_modules/openzwave-shared
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm info lifecycle openzwave-shared@1.5.6~install: Failed to exec install script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-21T12_15_29_718Z-debug.log
```

**Comment by Qaldak** [comment]
I found it. open-zwave was not installed.
https://github.com/OpenZWave/node-openzwave-shared/issues/322#issuecomment-508726903

**Comment by Qaldak** [comment]
same problem: https://github.com/OpenZWave/node-openzwave-shared/issues/322#issuecomment-508726903

**Comment by Qaldak** [comment]
via docker exec -u root node-red /bin/bash I installed the prerequisites.

after that I installed "node-red-contrib-openzwave" via Node-RED itself. After this, Node-RED was broken:
```
npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.,
npm ERR! This is most likely a problem with the node-red-docker package,,
npm ERR! not with npm itself.,
npm ERR! Tell the author that this fails on your system:,
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
npm ERR! You can get their info via:,
npm ERR!     npm owner ls node-red-docker,
npm ERR! There is likely additional logging output above.,
,
npm ERR! Please include the following file with any support request:,
npm ERR!     /usr/src/node-red/npm-debug.log,
npm info it worked if it ends with ok,
npm info using npm@2.14.7,
m info using node@v4.2.1,
npm info prestart node-red-docker@1.0.0,
npm info start node-red-docker@1.0.0,
,
> node-red-docker@1.0.0 start /usr/src/node-red,
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
,
/usr/src/node-red/node_modules/fs-extra/lib/fs/index.js:93,
exports.write = function (fd, buffer, ...args) {,
                                      ^^^,
,
SyntaxError: Unexpected token ...,
    at exports.runInThisContext (vm.js:53:16),
    at Module._compile (module.js:414:25),
    at Object.Module._extensions..js (module.js:442:10),
    at Module.load (module.js:356:32),
    at Function.Module._load (module.js:311:12),
    at Module.require (module.js:366:17),
    at require (module.js:385:17),
    at Object.<anonymous> (/usr/src/node-red/node_modules/fs-extra/lib/index.js:6:3),
    at Module._compile (module.js:435:26),
    at Object.Module._extensions..js (module.js:442:10),
,
npm info node-red-docker@1.0.0 Failed to exec start script,
m ERR! Linux 4.14.97-v7+,
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data",
npm ERR! node v4.2.1,
npm ERR! npm  v2.14.7,
npm ERR! code ELIFECYCLE,
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`,
npm ERR! Exit status 1,STX,
```

**Comment by Qaldak** [comment]
This was the problem:
wget http://node-arm.herokuapp.com/node_latest_armhf.deb && sudo dpkg -i node_latest_armhf.deb
(--> according https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md)

because this installed node version 4.2.1

**Comment by FilipHarald** [comment]
If you got here while troubleshooting openzwave + docker + node-red-contrib-openzwave . The answer is not that the node version is wrong/too low. It is because the docker container does not have access to all the files that Openzwave and openzwave-shared requires.

For now I am instead using a local node-red without any problems.

**Comment by ithinuel** [comment]
For what it's worth :
Following https://github.com/OpenZWave/openzwave-docker#expected-usage
I added `COPY --from=build /usr/local/include/openzwave /usr/local/include/openzwave`

```dockerfile
FROM chrisns/openzwave:alpine as build

FROM nodered/node-red

COPY --from=build /openzwave/libopenzwave.so* /lib/
COPY --from=build /openzwave/config /usr/local/etc/openzwave
COPY --from=build /usr/local/include/openzwave /usr/local/include/openzwave

ENV LD_LIBRARY_PATH /lib

RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production
```

This builds & runs. I can install `node-red-contrib-openzwave` from the palette manager.
